"""Generate the synthetic demo dataset backing the web proof of concept.

The output is written to ``data/web/demo/`` and is committed to the repository so
that a fresh clone can run the frontend and backend with no external downloads.

THE OUTPUT IS SYNTHETIC. Sample names, the motif pool and every distribution in
the reference-screen section are measured from the real HPRC callset so the
shapes look right, but the real table is never read here and every locus,
coordinate, allele, verdict and reference repeat below is generated by this
script. It is not a result.

    cd backend && uv run python scripts/make_demo_data.py
"""

import random
from pathlib import Path

import pandas as pd

SEED = 20260826
OUT = Path(__file__).resolve().parents[2] / "data" / "web" / "demo"

# The 68 samples in the merged HPRC + CHM13 callset, in VCF column order.
SAMPLES = """
HG00290 HG00320 HG00321 HG00329 HG00350 HG00408 HG00597 HG00609 HG00639 HG01081
HG01255 HG01346 HG01433 HG01496 HG01786 HG01975 HG01993 HG02004 HG02040 HG02071
HG02132 HG02135 HG02280 HG02293 HG02392 HG02572 HG02583 HG02602 HG02630 HG02698
HG02723 HG02818 HG02922 HG02984 HG03017 HG03209 HG03453 HG03521 HG03710 HG03804
HG03816 HG04157 HG04228 NA18505 NA18508 NA18608 NA18620 NA18948 NA18952 NA18960
NA18974 NA19240 NA19682 NA19776 NA19835 NA19909 NA20129 NA20282 NA20346 NA20762
NA20806 NA20809 NA20870 NA21093 NA21106 NA21110 NA21309 chm13_pacbio
""".split()

# GRCh38 primary assembly lengths.
CHROMS = {
    "chr1": 248956422, "chr2": 242193529, "chr3": 198295559, "chr4": 190214555,
    "chr5": 181538259, "chr6": 170805979, "chr7": 159345973, "chr8": 145138636,
    "chr9": 138394717, "chr10": 133797422, "chr11": 135086622, "chr12": 133275309,
    "chr13": 114364328, "chr14": 107043718, "chr15": 101991189, "chr16": 90338345,
    "chr17": 83257441, "chr18": 80373285, "chr19": 58617616, "chr20": 64444167,
    "chr21": 46709983, "chr22": 50818468, "chrX": 156040895,
}

# Observed motifs from the real callset, already collapsed to canonical form.
SEED_MOTIFS = """
AT TG AC CTC CAC TGG TC GA AAAT AG CCTC GGGA TGGC AAAC AGGG CCA AGGC TTTA GCCT
ATATA CCT CCCT TTTC TTTG GTG AGGA GGT ACC ATTCC CAT TGA AAT TATATAT AGCC AAAG
ATA TCTT CCTT TTG TCCT CCCCT TGGA TCCAT TCC AAGG GGGGA AGG CCG GCC CGG CCCTAA
AATGG GGAAT CCATT AAAGG CCTTT AGAGG TCTCC AAAAT ATTTT GGGGC AGGGG CCCCA
""".split()

# Real genes with known pathogenic tandem repeats, plus filler locus names.
DISEASE_GENES = [
    "XYLT1", "RFC1", "DMPK", "FMR1", "HTT", "C9orf72", "NOTCH2NLC", "ATXN1",
    "ATXN2", "ATXN3", "ATXN7", "CACNA1A", "TBP", "AR", "FXN", "CSTB", "JPH3",
    "PPP2R2B", "NOP56", "DAB1", "BEAN1", "TCF4", "GLS", "ZFHX3", "ABCD3",
]
OTHER_GENES = [
    "PRDM9", "MUC1", "ACAN", "TENM3", "CACNA1C", "NRXN1", "CNTNAP2", "RBFOX1",
    "MACF1", "PLEC", "AHNAK2", "TTN", "OBSCN", "SYNE1", "DST", "FLG", "HRNR",
    "GOLGA6L2", "ZNF91", "ZNF208", "TRIM48", "NBPF19", "LPA", "INS", "SLC6A4",
]


def canonical_motif(motif: str) -> str:
    """Collapse a motif to the lexicographically smallest rotation of itself or
    its reverse complement, so AT/TA and TG/GT/AC/CA land in one bucket."""
    motif = motif.upper()
    rc = motif.translate(str.maketrans("ACGT", "TGCA"))[::-1]
    rotations = [motif[i:] + motif[:i] for i in range(len(motif))]
    rotations += [rc[i:] + rc[:i] for i in range(len(rc))]
    return min(rotations)


def motif_class(motif_len: int) -> str:
    """The three classes a motif length falls in: 1bp, 2-6bp, >=7bp.

    There is no fourth class between STR and VNTR. A 7bp unit and a 40bp one
    behave the same way against a reference catalogue -- neither is short enough
    for the consensus sequence to be trusted base for base -- so a middle class
    would be drawing a line the data does not have. 6bp is the same boundary
    `novelty.motifs.STR_MAX_MOTIF` draws.
    """
    if motif_len == 1:
        return "homopolymer"
    if motif_len <= 6:
        return "STR"
    return "VNTR"


def random_motif(rng: random.Random, target_len: int) -> str:
    """Draw a motif of roughly ``target_len`` bp, reusing observed motifs where
    one fits and synthesising a plausible GC-skewed motif otherwise."""
    fits = [m for m in SEED_MOTIFS if len(m) == target_len]
    if fits and rng.random() < 0.75:
        return canonical_motif(rng.choice(fits))
    alphabet = "ACGT"
    weights = [0.29, 0.21, 0.21, 0.29]
    return canonical_motif("".join(rng.choices(alphabet, weights=weights, k=target_len)))


def draw_motif_length(rng: random.Random) -> int:
    """Match the motif-length mix measured in the real callset: ~28% homopolymer,
    ~58% STR, ~14% VNTR -- about 5 points of that VNTR share is 7-20bp and the
    rest is longer, which is why the draw below keeps the two ranges apart even
    though they are one class."""
    roll = rng.random()
    if roll < 0.28:
        return 1
    if roll < 0.86:
        return rng.choice([2, 2, 2, 3, 3, 4, 4, 5, 6])
    if roll < 0.91:
        return rng.randint(7, 20)
    return rng.randint(21, 90)


def draw_purity(rng: random.Random) -> float:
    """Real purity deciles run p10=0.63, p50=0.82, p90=1.0."""
    value = rng.betavariate(5.0, 1.6)
    return round(min(1.0, 0.55 + value * 0.45), 3)


# --------------------------------------------------------------------------- #
# The reference screen.
#
# Every constant in this section was measured on the real 27,853-locus HPRC
# callset -- data/HPRC_SV.survivor.ins.trf.tsv put through
# `novelty --platform ucsc,trexplorer` -- and then written down here as numbers.
# The real table is large, uncommitted and NOT read by this script: only its
# shape is reproduced, so a fresh clone renders a reference comparison whose
# proportions are right while every individual value stays generated.
#
# The VNTR row of each table below is the 7-20bp and >20bp measurements pooled
# on their class shares (5:9), from back when those were two classes. They are
# close enough to each other that pooling them changes little, but they are one
# arithmetic step further from the callset than the rest -- re-measure to make
# them first-hand again.
#
# Re-measure with:
#   uv run novelty --platform ucsc,trexplorer annotate IN.trf.tsv OUT.tsv
# --------------------------------------------------------------------------- #

#: Combined verdict per locus, conditioned on motif class. The gradient is the
#: finding, not a modelling choice: homopolymers are overwhelmingly novel_locus
#: because a poly-A tail on a mobile element lands where the reference annotates
#: no repeat, while VNTRs almost always have *something* nearby and differ in
#: motif instead.
NOVELTY_BY_CLASS = {
    "homopolymer": {"known": 0.058, "novel_motif": 0.149, "novel_locus": 0.792},
    "STR":         {"known": 0.546, "novel_motif": 0.285, "novel_locus": 0.168},
    "VNTR":        {"known": 0.531, "novel_motif": 0.445, "novel_locus": 0.024},
}

#: How the two catalogs split, given the combined verdict. The combined verdict
#: is the least novel of the pair, so `known` is reachable from either catalog
#: alone -- and in the real data it usually is: only 57% of known loci are known
#: to both. Sampling the pair jointly rather than independently keeps that
#: disagreement structure, which is what the U/T badge exists to show.
PLATFORM_SPLIT = {
    "known": [
        (("known", "known"), 0.570),
        (("novel_motif", "known"), 0.322),
        (("novel_locus", "known"), 0.069),
        (("known", "novel_motif"), 0.033),
        (("known", "novel_locus"), 0.006),
    ],
    "novel_motif": [
        (("novel_motif", "novel_motif"), 0.813),
        (("novel_motif", "novel_locus"), 0.100),
        (("novel_locus", "novel_motif"), 0.088),
    ],
    "novel_locus": [(("novel_locus", "novel_locus"), 1.0)],
}

#: Span in bp of the matched UCSC repeat, as (p10, p50, p90) per motif class.
#: The real tail runs to 500 kb; it is capped here at 3x p90 so one outlier
#: cannot flatten every allele bar sharing the track's scale.
UCSC_SPAN = {
    "homopolymer": (42, 568, 5819),
    "STR": (51, 322, 2197),
    "VNTR": (114, 449, 1508),
}
TREXPLORER_SPAN = (10, 165, 1262)

#: TRF percent identity of the matched UCSC repeat, 0-100. Never 100 in practice
#: -- a reference repeat perfect enough to score 100 is the exception.
UCSC_PER_MATCH = (68, 81, 97)

#: Period of the matched UCSC repeat when it does NOT match ours. On a `known`
#: call the periods agree 91.5% of the time, so that case is handled separately.
UCSC_NOVEL_PERIOD = (3, 20, 77)

#: Fraction of the inserted sequence that is tandem repeat at all. This is the
#: column that separates a real novel TR from a mobile element carrying a
#: poly-A tail, and the class gradient is dramatic: homopolymer loci sit at 0.09,
#: VNTRs at 0.89.
INSERTION_PURITY = {
    "homopolymer": (0.035, 0.089, 0.197),
    "STR": (0.059, 0.560, 0.956),
    "VNTR": (0.594, 0.891, 0.979),
}

#: Reference repeats within the 10 bp window, given at least one. UCSC annotates
#: about half as densely as TRExplorer, which is 5.6M loci against 1.05M.
UCSC_N_NEARBY = {1: 0.322, 2: 0.231, 3: 0.244, 4: 0.112, 5: 0.051, 6: 0.023, 7: 0.012, 8: 0.005}
TREXPLORER_N_NEARBY = {1: 0.188, 2: 0.164, 3: 0.135, 4: 0.093, 5: 0.077, 6: 0.085, 7: 0.060, 8: 0.045}

#: How often the insertion point falls *inside* the matched repeat rather than
#: within the window beside it.
UCSC_DISTANCE_ZERO = 0.937
TREXPLORER_DISTANCE_ZERO = 0.803

#: The window `novelty annotate` was run with. A repeat further than this from
#: the insertion point does not count as being at this locus.
WINDOW_BP = 10

#: Longest motif the screen compares approximately, and so the longest reference
#: consensus worth generating here. Matches `novelty --max-fuzzy-motif`.
MAX_MOTIF_BP = 200


def draw_quantile(rng: random.Random, anchors: tuple[float, float, float],
                  lo: float, hi: float) -> float:
    """Draw from a distribution given only its p10, p50 and p90.

    Piecewise-linear in quantile space. This hits the three measured anchors
    exactly and assumes nothing else about the shape, which is the right trade
    for reproducing a table that was never going to be lognormal anyway.
    """
    p10, p50, p90 = anchors
    q = rng.random()
    if q < 0.10:
        return lo + (p10 - lo) * (q / 0.10)
    if q < 0.50:
        return p10 + (p50 - p10) * ((q - 0.10) / 0.40)
    if q < 0.90:
        return p50 + (p90 - p50) * ((q - 0.50) / 0.40)
    return p90 + (hi - p90) * ((q - 0.90) / 0.10)


def draw_n_nearby(rng: random.Random, table: dict[int, float]) -> int:
    """Sample a repeat count; weights need not sum to 1, the tail is truncated."""
    return rng.choices(list(table), weights=list(table.values()), k=1)[0]


def rotate(rng: random.Random, motif: str) -> str:
    """A random rotation of a motif.

    Both sides of the comparison are TRF output, and the phase TRF picks is an
    artifact of where it started rather than a property of the repeat -- our
    CCCTAA against the reference's ACCCTA is one repeat, not two. The screen
    canonicalizes rotations away; the demo has to produce them for there to be
    anything to canonicalize.
    """
    if len(motif) < 2:
        return motif
    offset = rng.randrange(len(motif))
    return motif[offset:] + motif[:offset]


def unrelated_motif(rng: random.Random, motif: str, length: int) -> str:
    """A motif of `length` bp that is not equivalent to `motif`.

    Rejection sampling against the canonical form, because a `novel_motif`
    verdict whose reference motif happens to canonicalize to ours would be a
    contradiction rendered on the page.
    """
    target = canonical_motif(motif)
    for _ in range(24):
        candidate = "".join(rng.choices("ACGT", weights=[0.29, 0.21, 0.21, 0.29], k=length))
        if canonical_motif(candidate) != target:
            return candidate
    return candidate


def screen_locus(rng: random.Random, motif: str, mclass: str, pos: int) -> dict:
    """Generate one locus's reference-screen columns.

    Mirrors the output of `novelty annotate --platform ucsc,trexplorer`: a
    combined verdict, then an independent block per catalog. A catalog that found
    nothing gets None throughout rather than a zero -- "no repeat annotated here"
    and "a repeat of length zero" are different statements, and the interface
    renders them differently.
    """
    verdicts = NOVELTY_BY_CLASS[mclass]
    novelty = rng.choices(list(verdicts), weights=list(verdicts.values()), k=1)[0]

    pairs = PLATFORM_SPLIT[novelty]
    ucsc_verdict, trex_verdict = rng.choices(
        [pair for pair, _ in pairs], weights=[weight for _, weight in pairs], k=1
    )[0]

    row: dict = {
        "novelty": novelty,
        "insertion_purity": round(
            min(0.999, max(0.001, draw_quantile(rng, INSERTION_PURITY[mclass], 0.0, 1.0))), 3
        ),
    }

    for platform, verdict in (("ucsc", ucsc_verdict), ("trexplorer", trex_verdict)):
        row.update(screen_platform(rng, platform, verdict, motif, mclass, pos))

    # `catalogs` is the list of catalogs that actually contain this repeat, which
    # is exactly the set whose verdict is `known`. That keeps it consistent with
    # the combined verdict by construction: non-empty iff `known`.
    row["catalogs"] = ";".join(
        label
        for platform, label in (("ucsc", "UCSC simpleRepeat"), ("trexplorer", "TRExplorer"))
        if row[f"{platform}_novelty"] == "known"
    )
    row["novel"] = novelty != "known"
    return row


def screen_platform(rng: random.Random, platform: str, verdict: str,
                    motif: str, mclass: str, pos: int) -> dict:
    """One catalog's block of columns for one locus."""
    prefix = f"{platform}_"
    empty = {
        f"{prefix}novelty": verdict,
        f"{prefix}n_nearby": 0,
        f"{prefix}start": None,
        f"{prefix}end": None,
        f"{prefix}distance": None,
        f"{prefix}motif": None,
        f"{prefix}motif_edits": None,
    }
    if platform == "ucsc":
        empty.update({"ucsc_period": None, "ucsc_copy_num": None, "ucsc_per_match": None})

    if verdict == "novel_locus":
        return empty

    if platform == "ucsc":
        anchors, lo = UCSC_SPAN[mclass], 24
        n_nearby = draw_n_nearby(rng, UCSC_N_NEARBY)
        overlapping = rng.random() < UCSC_DISTANCE_ZERO
    else:
        anchors, lo = TREXPLORER_SPAN, 6
        n_nearby = draw_n_nearby(rng, TREXPLORER_N_NEARBY)
        overlapping = rng.random() < TREXPLORER_DISTANCE_ZERO

    if verdict == "known":
        # The same repeat, reported at whatever phase TRF happened to pick.
        ref_motif = rotate(rng, motif)
        period = len(motif)
    else:
        period = round(draw_quantile(rng, UCSC_NOVEL_PERIOD, 1, MAX_MOTIF_BP))
        period = max(1, min(MAX_MOTIF_BP, period))
        ref_motif = unrelated_motif(rng, motif, period)

    # Span has to hold at least ~2 copies of the unit, or the reported copy
    # number contradicts the reported span.
    span = round(draw_quantile(rng, anchors, lo, anchors[2] * 3))
    span = max(span, int(period * 1.8), lo)

    distance = 0 if overlapping else rng.randint(1, WINDOW_BP)
    if distance == 0:
        start = pos - rng.randrange(span)
    else:
        start = pos + distance if rng.random() < 0.5 else pos - distance - span

    block = {
        f"{prefix}novelty": verdict,
        f"{prefix}n_nearby": n_nearby,
        f"{prefix}start": max(1, start),
        f"{prefix}end": max(1, start) + span,
        f"{prefix}distance": distance,
        f"{prefix}motif": ref_motif,
        # With motif tolerance off, this is binary rather than a distance: 0 when
        # the motifs are equivalent, 1 when they are not. See NOVELTY_SCREEN.md.
        f"{prefix}motif_edits": 0 if verdict == "known" else 1,
    }
    if platform == "ucsc":
        block.update({
            "ucsc_period": period,
            "ucsc_copy_num": round(span / period, 1),
            "ucsc_per_match": round(draw_quantile(rng, UCSC_PER_MATCH, 59, 100)),
        })
    return block


def build(n_loci: int = 1200) -> tuple[pd.DataFrame, pd.DataFrame]:
    rng = random.Random(SEED)
    chrom_names = list(CHROMS)
    chrom_weights = [CHROMS[c] for c in chrom_names]

    loci_rows: list[dict] = []
    segment_rows: list[dict] = []

    for i in range(n_loci):
        locus_id = f"TRL{i + 1:06d}"
        chrom = rng.choices(chrom_names, weights=chrom_weights, k=1)[0]
        pos = rng.randint(1_000_000, CHROMS[chrom] - 1_000_000)

        motif_len = draw_motif_length(rng)
        motif = random_motif(rng, motif_len)
        motif_len = len(motif)
        mclass = motif_class(motif_len)

        screen = screen_locus(rng, motif, mclass, pos)
        novel = screen["novel"]

        # Novel loci skew toward lower cohort support: that is what makes them
        # easy for a catalog-first pipeline to miss in the first place.
        if novel:
            n_samples = max(1, min(68, int(rng.betavariate(1.6, 4.5) * 68)))
        else:
            n_samples = max(1, min(68, int(rng.betavariate(3.2, 2.0) * 68)))

        # Long-motif loci are more likely to sit in a gene body worth naming.
        if rng.random() < (0.10 if mclass in ("homopolymer", "STR") else 0.30):
            gene = rng.choice(DISEASE_GENES)
            disease_gene = True
        elif rng.random() < 0.35:
            gene = rng.choice(OTHER_GENES)
            disease_gene = False
        else:
            gene = None
            disease_gene = False

        carriers = rng.sample(SAMPLES, n_samples)
        base_units = max(3, int(rng.lognormvariate(2.6, 0.75)))
        purities: list[float] = []
        lengths: list[int] = []

        for sample in carriers:
            # Allele-level copy-number jitter around the locus mean.
            units = max(2, int(rng.gauss(base_units, max(1.0, base_units * 0.28))))
            purity = draw_purity(rng)
            purities.append(purity)

            cursor = 0
            seg_index = 0

            # About half of real (sample, SV) records carry more than one detected
            # repeat, so compound structure has to be representable.
            n_blocks = 1
            if rng.random() < 0.42:
                n_blocks = rng.choice([2, 2, 2, 3, 3, 4])

            # Leading non-repetitive flank on some alleles.
            if rng.random() < 0.45:
                flank = rng.randint(8, 60)
                segment_rows.append({
                    "locus_id": locus_id, "sample": sample, "seg_index": seg_index,
                    "seg_type": "flank", "start": cursor, "end": cursor + flank,
                    "motif": None, "purity": None, "units": None,
                })
                cursor += flank
                seg_index += 1

            for block in range(n_blocks):
                block_motif = motif if block == 0 else random_motif(rng, draw_motif_length(rng))
                block_units = units if block == 0 else max(2, int(units * rng.uniform(0.2, 0.7)))
                block_purity = purity if block == 0 else draw_purity(rng)
                span = len(block_motif) * block_units
                segment_rows.append({
                    "locus_id": locus_id, "sample": sample, "seg_index": seg_index,
                    "seg_type": "repeat", "start": cursor, "end": cursor + span,
                    "motif": block_motif, "purity": block_purity, "units": block_units,
                })
                cursor += span
                seg_index += 1

                if block < n_blocks - 1 and rng.random() < 0.55:
                    spacer = rng.randint(5, 40)
                    segment_rows.append({
                        "locus_id": locus_id, "sample": sample, "seg_index": seg_index,
                        "seg_type": "flank", "start": cursor, "end": cursor + spacer,
                        "motif": None, "purity": None, "units": None,
                    })
                    cursor += spacer
                    seg_index += 1

            if rng.random() < 0.45:
                flank = rng.randint(8, 60)
                segment_rows.append({
                    "locus_id": locus_id, "sample": sample, "seg_index": seg_index,
                    "seg_type": "flank", "start": cursor, "end": cursor + flank,
                    "motif": None, "purity": None, "units": None,
                })
                cursor += flank

            lengths.append(cursor)

        loci_rows.append({
            "locus_id": locus_id,
            "chrom": chrom,
            "pos": pos,
            "motif": motif,
            "motif_len": motif_len,
            "motif_class": mclass,
            "n_samples": n_samples,
            "median_len": int(pd.Series(lengths).median()),
            "min_len": int(min(lengths)),
            "max_len": int(max(lengths)),
            "mean_purity": round(sum(purities) / len(purities), 3),
            "gene": gene,
            "disease_gene": disease_gene,
            # The reference screen: the combined verdict, then one block per
            # catalog. `novel` and `catalogs` come from here too, so the boolean
            # and the three-valued verdict cannot contradict each other.
            **screen,
        })

    loci = pd.DataFrame(loci_rows)

    # A catalog that found nothing leaves every one of its columns empty, which
    # in a plain float column means NaN -- and NaN is not valid JSON, nor is a
    # genomic coordinate a decimal. Nullable integers keep the empty case a real
    # null all the way to the browser, and keep `ucsc_start` printable as a
    # coordinate rather than as 13325101.0.
    integer_columns = [
        f"{platform}_{field}"
        for platform in ("ucsc", "trexplorer")
        for field in ("n_nearby", "start", "end", "distance", "motif_edits")
    ] + ["ucsc_period", "ucsc_per_match"]
    for column in integer_columns:
        loci[column] = loci[column].astype("Int64")

    return loci, pd.DataFrame(segment_rows)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    loci, segments = build()

    loci.to_parquet(OUT / "loci.parquet", index=False)
    segments.to_parquet(OUT / "segments.parquet", index=False)

    print(f"wrote {len(loci):,} loci    -> {OUT / 'loci.parquet'}")
    print(f"wrote {len(segments):,} segments -> {OUT / 'segments.parquet'}")
    print()
    print("motif class mix:")
    print(loci["motif_class"].value_counts().to_string())
    print()
    print("screen verdict, per locus:")
    print(loci["novelty"].value_counts().to_string())
    print()
    print("verdict by motif class (row-normalised, compare with NOVELTY_BY_CLASS):")
    print(
        pd.crosstab(loci["motif_class"], loci["novelty"], normalize="index")
        .round(3)
        .to_string()
    )
    print()
    print(f"novel loci: {int(loci['novel'].sum()):,} / {len(loci):,} "
          f"({100 * loci['novel'].mean():.1f}%)")
    print(f"novel & in a disease gene: {int((loci['novel'] & loci['disease_gene']).sum()):,}")
    print(f"catalogs disagree: "
          f"{int((loci['ucsc_novelty'] != loci['trexplorer_novelty']).sum()):,}")


if __name__ == "__main__":
    main()
