"""Generate the synthetic demo dataset backing the web proof of concept.

The output is written to ``data/web/demo/`` and is committed to the repository so
that a fresh clone can run the frontend and backend with no external downloads.

THE OUTPUT IS SYNTHETIC. Sample names and the motif pool are taken from the real
HPRC callset so the shapes look right, but every locus, coordinate, allele and
catalog membership below is generated by this script. It is not a result.

    cd backend && uv run python scripts/make_demo_data.py
"""

import random
from pathlib import Path

import pandas as pd

SEED = 20260826
OUT = Path(__file__).resolve().parents[2] / "data" / "web" / "demo"

# The 68 samples in the merged HPRC + CHM13 callset, in VCF column order.
SAMPLES = """
HG00290 HG00320 HG00321 HG00329 HG00350 HG00408 HG00597 HG00609 HG00639 HG01081
HG01255 HG01346 HG01433 HG01496 HG01786 HG01975 HG01993 HG02004 HG02040 HG02071
HG02132 HG02135 HG02280 HG02293 HG02392 HG02572 HG02583 HG02602 HG02630 HG02698
HG02723 HG02818 HG02922 HG02984 HG03017 HG03209 HG03453 HG03521 HG03710 HG03804
HG03816 HG04157 HG04228 NA18505 NA18508 NA18608 NA18620 NA18948 NA18952 NA18960
NA18974 NA19240 NA19682 NA19776 NA19835 NA19909 NA20129 NA20282 NA20346 NA20762
NA20806 NA20809 NA20870 NA21093 NA21106 NA21110 NA21309 chm13_pacbio
""".split()

# GRCh38 primary assembly lengths.
CHROMS = {
    "chr1": 248956422, "chr2": 242193529, "chr3": 198295559, "chr4": 190214555,
    "chr5": 181538259, "chr6": 170805979, "chr7": 159345973, "chr8": 145138636,
    "chr9": 138394717, "chr10": 133797422, "chr11": 135086622, "chr12": 133275309,
    "chr13": 114364328, "chr14": 107043718, "chr15": 101991189, "chr16": 90338345,
    "chr17": 83257441, "chr18": 80373285, "chr19": 58617616, "chr20": 64444167,
    "chr21": 46709983, "chr22": 50818468, "chrX": 156040895,
}

# Observed motifs from the real callset, already collapsed to canonical form.
SEED_MOTIFS = """
AT TG AC CTC CAC TGG TC GA AAAT AG CCTC GGGA TGGC AAAC AGGG CCA AGGC TTTA GCCT
ATATA CCT CCCT TTTC TTTG GTG AGGA GGT ACC ATTCC CAT TGA AAT TATATAT AGCC AAAG
ATA TCTT CCTT TTG TCCT CCCCT TGGA TCCAT TCC AAGG GGGGA AGG CCG GCC CGG CCCTAA
AATGG GGAAT CCATT AAAGG CCTTT AGAGG TCTCC AAAAT ATTTT GGGGC AGGGG CCCCA
""".split()

# Real genes with known pathogenic tandem repeats, plus filler locus names.
DISEASE_GENES = [
    "XYLT1", "RFC1", "DMPK", "FMR1", "HTT", "C9orf72", "NOTCH2NLC", "ATXN1",
    "ATXN2", "ATXN3", "ATXN7", "CACNA1A", "TBP", "AR", "FXN", "CSTB", "JPH3",
    "PPP2R2B", "NOP56", "DAB1", "BEAN1", "TCF4", "GLS", "ZFHX3", "ABCD3",
]
OTHER_GENES = [
    "PRDM9", "MUC1", "ACAN", "TENM3", "CACNA1C", "NRXN1", "CNTNAP2", "RBFOX1",
    "MACF1", "PLEC", "AHNAK2", "TTN", "OBSCN", "SYNE1", "DST", "FLG", "HRNR",
    "GOLGA6L2", "ZNF91", "ZNF208", "TRIM48", "NBPF19", "LPA", "INS", "SLC6A4",
]


def canonical_motif(motif: str) -> str:
    """Collapse a motif to the lexicographically smallest rotation of itself or
    its reverse complement, so AT/TA and TG/GT/AC/CA land in one bucket."""
    motif = motif.upper()
    rc = motif.translate(str.maketrans("ACGT", "TGCA"))[::-1]
    rotations = [motif[i:] + motif[:i] for i in range(len(motif))]
    rotations += [rc[i:] + rc[:i] for i in range(len(rc))]
    return min(rotations)


def motif_class(motif_len: int) -> str:
    if motif_len == 1:
        return "homopolymer"
    if motif_len <= 6:
        return "STR"
    if motif_len <= 20:
        return "mid"
    return "VNTR"


def random_motif(rng: random.Random, target_len: int) -> str:
    """Draw a motif of roughly ``target_len`` bp, reusing observed motifs where
    one fits and synthesising a plausible GC-skewed motif otherwise."""
    fits = [m for m in SEED_MOTIFS if len(m) == target_len]
    if fits and rng.random() < 0.75:
        return canonical_motif(rng.choice(fits))
    alphabet = "ACGT"
    weights = [0.29, 0.21, 0.21, 0.29]
    return canonical_motif("".join(rng.choices(alphabet, weights=weights, k=target_len)))


def draw_motif_length(rng: random.Random) -> int:
    """Match the motif-length mix measured in the real callset: ~28% homopolymer,
    ~58% STR, ~5% 7-20bp, ~9% VNTR."""
    roll = rng.random()
    if roll < 0.28:
        return 1
    if roll < 0.86:
        return rng.choice([2, 2, 2, 3, 3, 4, 4, 5, 6])
    if roll < 0.91:
        return rng.randint(7, 20)
    return rng.randint(21, 90)


def draw_purity(rng: random.Random) -> float:
    """Real purity deciles run p10=0.63, p50=0.82, p90=1.0."""
    value = rng.betavariate(5.0, 1.6)
    return round(min(1.0, 0.55 + value * 0.45), 3)


def catalog_membership(rng: random.Random, mclass: str) -> list[str]:
    """Existing catalogs are built from reference-anchored short-read panels, so
    they cover short STRs well and long non-reference VNTRs poorly. That gradient
    is the whole point of the demo, so it is modelled explicitly."""
    base = {"homopolymer": 0.82, "STR": 0.71, "mid": 0.34, "VNTR": 0.11}[mclass]
    hits = []
    if rng.random() < base:
        hits.append("TR-Explorer")
    if rng.random() < base * 0.75:
        hits.append("gnomAD-TR")
    if rng.random() < base * 0.25:
        hits.append("STRchive")
    return hits


def build(n_loci: int = 1200) -> tuple[pd.DataFrame, pd.DataFrame]:
    rng = random.Random(SEED)
    chrom_names = list(CHROMS)
    chrom_weights = [CHROMS[c] for c in chrom_names]

    loci_rows: list[dict] = []
    segment_rows: list[dict] = []

    for i in range(n_loci):
        locus_id = f"TRL{i + 1:06d}"
        chrom = rng.choices(chrom_names, weights=chrom_weights, k=1)[0]
        pos = rng.randint(1_000_000, CHROMS[chrom] - 1_000_000)

        motif_len = draw_motif_length(rng)
        motif = random_motif(rng, motif_len)
        motif_len = len(motif)
        mclass = motif_class(motif_len)

        catalogs = catalog_membership(rng, mclass)
        novel = not catalogs

        # Novel loci skew toward lower cohort support: that is what makes them
        # easy for a catalog-first pipeline to miss in the first place.
        if novel:
            n_samples = max(1, min(68, int(rng.betavariate(1.6, 4.5) * 68)))
        else:
            n_samples = max(1, min(68, int(rng.betavariate(3.2, 2.0) * 68)))

        # Long-motif loci are more likely to sit in a gene body worth naming.
        if rng.random() < (0.10 if mclass in ("homopolymer", "STR") else 0.30):
            gene = rng.choice(DISEASE_GENES)
            disease_gene = True
        elif rng.random() < 0.35:
            gene = rng.choice(OTHER_GENES)
            disease_gene = False
        else:
            gene = None
            disease_gene = False

        carriers = rng.sample(SAMPLES, n_samples)
        base_units = max(3, int(rng.lognormvariate(2.6, 0.75)))
        purities: list[float] = []
        lengths: list[int] = []

        for sample in carriers:
            # Allele-level copy-number jitter around the locus mean.
            units = max(2, int(rng.gauss(base_units, max(1.0, base_units * 0.28))))
            purity = draw_purity(rng)
            purities.append(purity)

            cursor = 0
            seg_index = 0

            # About half of real (sample, SV) records carry more than one detected
            # repeat, so compound structure has to be representable.
            n_blocks = 1
            if rng.random() < 0.42:
                n_blocks = rng.choice([2, 2, 2, 3, 3, 4])

            # Leading non-repetitive flank on some alleles.
            if rng.random() < 0.45:
                flank = rng.randint(8, 60)
                segment_rows.append({
                    "locus_id": locus_id, "sample": sample, "seg_index": seg_index,
                    "seg_type": "flank", "start": cursor, "end": cursor + flank,
                    "motif": None, "purity": None, "units": None,
                })
                cursor += flank
                seg_index += 1

            for block in range(n_blocks):
                block_motif = motif if block == 0 else random_motif(rng, draw_motif_length(rng))
                block_units = units if block == 0 else max(2, int(units * rng.uniform(0.2, 0.7)))
                block_purity = purity if block == 0 else draw_purity(rng)
                span = len(block_motif) * block_units
                segment_rows.append({
                    "locus_id": locus_id, "sample": sample, "seg_index": seg_index,
                    "seg_type": "repeat", "start": cursor, "end": cursor + span,
                    "motif": block_motif, "purity": block_purity, "units": block_units,
                })
                cursor += span
                seg_index += 1

                if block < n_blocks - 1 and rng.random() < 0.55:
                    spacer = rng.randint(5, 40)
                    segment_rows.append({
                        "locus_id": locus_id, "sample": sample, "seg_index": seg_index,
                        "seg_type": "flank", "start": cursor, "end": cursor + spacer,
                        "motif": None, "purity": None, "units": None,
                    })
                    cursor += spacer
                    seg_index += 1

            if rng.random() < 0.45:
                flank = rng.randint(8, 60)
                segment_rows.append({
                    "locus_id": locus_id, "sample": sample, "seg_index": seg_index,
                    "seg_type": "flank", "start": cursor, "end": cursor + flank,
                    "motif": None, "purity": None, "units": None,
                })
                cursor += flank

            lengths.append(cursor)

        loci_rows.append({
            "locus_id": locus_id,
            "chrom": chrom,
            "pos": pos,
            "motif": motif,
            "motif_len": motif_len,
            "motif_class": mclass,
            "n_samples": n_samples,
            "median_len": int(pd.Series(lengths).median()),
            "min_len": int(min(lengths)),
            "max_len": int(max(lengths)),
            "mean_purity": round(sum(purities) / len(purities), 3),
            "novel": novel,
            "catalogs": ";".join(catalogs),
            "gene": gene,
            "disease_gene": disease_gene,
        })

    return pd.DataFrame(loci_rows), pd.DataFrame(segment_rows)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    loci, segments = build()

    loci.to_parquet(OUT / "loci.parquet", index=False)
    segments.to_parquet(OUT / "segments.parquet", index=False)

    print(f"wrote {len(loci):,} loci    -> {OUT / 'loci.parquet'}")
    print(f"wrote {len(segments):,} segments -> {OUT / 'segments.parquet'}")
    print()
    print("motif class mix:")
    print(loci["motif_class"].value_counts().to_string())
    print()
    print(f"novel loci: {int(loci['novel'].sum()):,} / {len(loci):,} "
          f"({100 * loci['novel'].mean():.1f}%)")
    print(f"novel & in a disease gene: {int((loci['novel'] & loci['disease_gene']).sum()):,}")


if __name__ == "__main__":
    main()
