blank_issues_enabled: true
contact_links:
  - name: Team Slack
    url: https://baylorncbisvc-1jk9469.slack.com/archives/C0BRNLZDTL3
    about: Ask a quick question in the #2026_group2_group10_tandem_repeats channel.
